### ISSUE TITLE
CSS not seeming to load when added to site.

### ISSUE THREAD

**Issue by lewiscowper** [tessalt/echo-chamber-js#13]
<img width="791" alt="screen shot 2015-07-15 at 09 44 39" src="https://cloud.githubusercontent.com/assets/593574/8694332/22f9cbda-2ad6-11e5-8a25-606b29f15edd.png">

Looks like the href attribute of the stylesheet `link` tag is set to something that is a local site, but doesn't seem to pull it down into the iframe maybe?

<img width="561" alt="screen shot 2015-07-15 at 09 45 07" src="https://cloud.githubusercontent.com/assets/593574/8694360/49c15de6-2ad6-11e5-9a72-13c24d74517a.png">

Edit: It appears that it may never set EchoChamber.host to hosts.prod? If I manually change the href in that link tag to `https://s3.amazonaws.com/echochamberjs/dist/main.css` it works.

**Comment by geraldvillorente** [comment]
Same here CSS is not loading.
