### ISSUE TITLE
Missing donation button.

### ISSUE THREAD

**Issue by exaexa** [tessalt/echo-chamber-js#18]
Where can I send money for the author of this beautiful software?

She deserves a bottle of good wine or something.

Thanks for this thing.

-exa

**Comment by csaunders** [comment]
Way to assume gender bro.

**Comment by exaexa** [comment]
Oh!
Corrected.
I feel bad. :D

**Comment by csaunders** [comment]
Just play it safe and use gender neutral pronouns (or avoid them entirely) :)

**Comment by una** [comment]
:+1: to this entire thread

**Comment by virtadpt** [comment]
:+1: and donations would be forthcoming.  Perhaps on Patreon, so one could donate on a monthly basis?
