### ISSUE TITLE
comment storage

### ISSUE THREAD

**Issue by jfoucry** [tessalt/echo-chamber-js#33]
Hello,

I try ti install echo-chamber for my jekyll blog. It almost work, I found where translate it in french. It's great. But I can't figure where the comment are saved? I am not a javascript dev. 

Thanks in advance,
Jacques

**Comment by SimonAronsson** [comment]
Lololol

**Comment by nate-fr** [comment]
The comments are not saved. Read the project README.

**Comment by jfoucry** [comment]
Ok, I am stupid. Sorry, I did not understood.

**Comment by MartijnDwars** [comment]
Priceless.
