### ISSUE TITLE
node_modules should not be in git

### ISSUE THREAD

**Issue by souvik1997** [tessalt/echo-chamber-js#5]
node_modules should not be in the git repository since they are specified in package.json.

**Comment by tessalt** [comment]
lol whatever

**Comment by wesbos** [comment]
Best reply ever 👌🏻👌🏻👌🏻👌

**Comment by tylerball** [comment]
:joy: :joy:

**Comment by joejack23** [comment]
hi!!
im joe from bs.as. Argentina

**Comment by ccoenen** [comment]
Nein, ich möchte diesen Teppich nicht kaufen.

**Comment by syropian** [comment]
![Rekt](http://media.giphy.com/media/Ojd9pgisdY7Nm/giphy.gif)

**Comment by BrianS198** [comment]
:laughing: :+1:

**Comment by ahmadnassri** [comment]
:clap:
